services:
  twitter-x-backup:
    image: 192.168.2.141:5000/twitter-x-backup:latest
    pull_policy: always
    container_name: twitter-x-backup
    env_file:
      - .env
    environment:
      Aliases__I: /mnt/i
      # Aliases__K: /mnt/k
      Aliases__L: /mnt/l
      # Aliases__Q: /mnt/q
      # Aliases__R: /mnt/r
      Aliases__S: /mnt/s
      Aliases__J: /mnt/j
