services:
  twitter-x-backup-cli:
    image: 192.168.2.141:5000/twitter-x-backup-cli:latest
    pull_policy: always
    container_name: twitter-x-backup-cli
    env_file:
      - .env
    environment:
      BACKUP__Aliases__I: /mnt/i
      # BACKUP__Aliases__K: /mnt/k
      BACKUP__Aliases__L: /mnt/l
      # BACKUP__Aliases__Q: /mnt/q
      # BACKUP__Aliases__R: /mnt/r
      BACKUP__Aliases__S: /mnt/s
      BACKUP__Aliases__J: /mnt/j
